config/routes.rb
Rails.application.routes.draw do
  get "about", to:"about#index"
  # get "", to: "main#index"
  root to: "main#index"

  get "dashboard", to: "dashboard#index"

  get "profile", to: "profile#index"

  get "users_by_department", to: "users#users_by_department"
  
  get "login", to: "session#new"
  post "login", to: "session#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"
  
  get "signup", to: "registrations#new"
  post "signup", to: "registrations#create"
  
  delete "logout", to: "session#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "/non_verified_tasks", to: "tasks#non_verified_tasks"
  get "/non_verified_tasks/:id", to: "tasks#show_for_approval", as: "show_for_approval"
  put "/non_verified_tasks/:id/approve", to: "tasks#approve", as: "approve_task"

  get "/assigned_tasks", to: "tasks#assigned_tasks"
  get "/assigned_tasks/:id", to: "tasks#show_assigned_task", as: "show_assigned_task"
  put "/assigned_tasks/:id/mark_done", to: "tasks#mark_complete", as: "mark_complete"
  put "/assigned_tasks/:id/acknowledge_task", to: "tasks#acknowledge_task", as: "acknowledge_task"
  resources :tasks
  
  resources :users
  # Error routes
  # match '/404', to: 'errors#not_found', via: :all
  # match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      #send mail
      PasswordMailer.reset_password(@user).deliver_now
    end
  
    redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset you password"
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to login_path, alert: "Your token has been expired. Please try again."
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")

    if @user.update(password_params)
      redirect_to login_path, notice: "Your password as reset successfully. Please sign in."
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/password_resets/edit.html.erb
<% content_for(:title, "Reset Password | Task Manager") %>
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h1 class="mb-4 text-center">Reset your password?</h1>

          <div class="text-center mb-4">
            <img src="https://abhishekkamble.s3.ap-south-1.amazonaws.com/portfolio-images/resetpass.png" alt="Logo" class="rounded-circle" style="width: 100px; height: 100px;">
          </div>

          <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
            <% if @user.errors.any? %>
              <div class="alert alert-danger">
                <% @user.errors.full_messages.each do |messages| %>
                  <div><%= messages %></div>
                <% end %>
              <div>
            <% end %>
            
            <div class="mb-3">
              <%= form.label :password %>
              <%= form.password_field :password, class: "form-control", placeholder: "Your new password" %>
            </div>
            <div class="mb-3">
              <%= form.label :password_confirmation %>
              <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm new password" %>
            </div>

            <div class="mb-3 text-center">
              <%= form.submit "Reset Password", class: "btn btn-primary" %>
            </div>
          <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<% content_for(:title, "Forgot Password | Task Manager") %>
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h1 class="mb-4 text-center">Forgot your password?</h1>
          <div class="text-center mb-4">
            <img src="https://abhishekkamble.s3.ap-south-1.amazonaws.com/portfolio-images/resetpass.png" alt="Logo" class="rounded-circle" style="width: 100px; height: 100px;">
          </div>
          
          <%= form_with url: password_reset_path do |form| %>

            <div class="mb-3">
              <%= form.label :email %>
              <%= form.text_field :email, class: "form-control", placeholder: "abc@email.com" %>
            </div>

            <div class="mb-3 text-center">
              <%= form.submit "Reset Password", class: "btn btn-primary" %>
            </div>
          <% end %>
          </div>
      </div>
    </div>
  </div>
</div>