config/routes.rb
Rails.application.routes.draw do
  get "about", to:"about#index"
  # get "", to: "main#index"
  root to: "main#index"

  get "dashboard", to: "dashboard#index"

  get "profile", to: "profile#index"

  get "users_by_department", to: "users#users_by_department"
  
  get "login", to: "session#new"
  post "login", to: "session#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"
  
  get "signup", to: "registrations#new"
  post "signup", to: "registrations#create"
  
  delete "logout", to: "session#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "/non_verified_tasks", to: "tasks#non_verified_tasks"
  get "/non_verified_tasks/:id", to: "tasks#show_for_approval", as: "show_for_approval"
  put "/non_verified_tasks/:id/approve", to: "tasks#approve", as: "approve_task"

  get "/assigned_tasks", to: "tasks#assigned_tasks"
  get "/assigned_tasks/:id", to: "tasks#show_assigned_task", as: "show_assigned_task"
  put "/assigned_tasks/:id/mark_done", to: "tasks#mark_complete", as: "mark_complete"
  put "/assigned_tasks/:id/acknowledge_task", to: "tasks#acknowledge_task", as: "acknowledge_task"
  resources :tasks
  
  resources :users
  # Error routes
  # match '/404', to: 'errors#not_found', via: :all
  # match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: "creator_id"
  belongs_to :assignee, class_name: 'User', optional: true
  belongs_to :verifier, class_name: 'User', optional: true
  belongs_to :department, class_name: 'Department'

  validates :title, presence: true
  validates :description, presence: true
  validates :due_date, presence: true
  validates :status, presence: true
  validates :priority, presence: true
  validates :department_id, presence: true

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_login
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  helper TaskHelper

  def index
    @tasks = Current.user.tasks

    sort_by = params[:sort]

    case sort_by
    when 'priority'
      @tasks = @tasks.order(priority: :desc)
    when 'due_date'
      @tasks = @tasks.order(due_date: :asc) 
    when 'status'
      @tasks = @tasks.order(status: :asc) 
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Current.user.tasks.build
    @departments = Department.all.pluck(:name, :id)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Current.user.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @task = Current.user.tasks.build(task_params)
    @task.creator = Current.user    
    if @task.save
      redirect_to @task, notice: 'task was successfully created.'
    else
      @departments = Department.all.pluck(:name, :id)
      render :new
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: 'Task was successfully destroyed.'
  end

  def non_verified_tasks
    @non_verified_tasks = Task.where(verifier_id: nil).where.not(user_id: Current.user.id).where.not(assignee_id: Current.user.id)
  end

  def show_for_approval
    @task = Task.find(params[:id])
  end

  def approve
    @task = Task.find(params[:id])
    if @task.update(verifier_id: Current.user.id)
      redirect_to @task, notice: 'Task was successfully approved.'
    else
      redirect_to @task, alert: 'Failed to approve task.'
    end
  end

  def assigned_tasks
    @assigned_tasks = Task.where(assignee_id: Current.user.id)

    sort_by = params[:sort]

    case sort_by
    when 'priority'
      @assigned_tasks = @assigned_tasks.order(priority: :desc)
    when 'due_date'
      @assigned_tasks = @assigned_tasks.order(due_date: :asc) 
    when 'status'
      @assigned_tasks = @assigned_tasks.order(status: :asc) 
    end
  end

  def show_assigned_task
    @task = Task.find(params[:id])
  end

  def mark_complete
    @task = Task.find(params[:id])
    if @task.update(status: 3)
      redirect_to @task, notice: 'Task marked as completed.'
    else
      redirect_to @task, alert: 'Failed to mark the task as completed.'
    end
  end

  def acknowledge_task
    @task = Task.find(params[:id])
    if @task.update(status: 2)
      redirect_to @task, notice: 'Task marked as completed.'
    else
      redirect_to @task, alert: 'Failed to acknowledge the task.'
    end
  end

  private
    def set_task
      @task = Current.user.tasks.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :due_date, :status, :priority, :department_id, :assignee_id, :creator_id)
    end

    def require_login
      unless Current.user
        flash[:error] = "You must be logged in to access this section"
        redirect_to login_path
      end
    end
end

app/helpers/task_helper.rb
# app/helpers/task_helper.rb

module TaskHelper
  def task_status_background(status)
    case status
    when 1
      "background-color: #ffeeba;" # Faint yellow for pending tasks
    when 2
      "background-color: #cce5ff;" # Faint blue for in progress tasks
    when 3
      "background-color: #d4edda;" # Faint green for completed tasks
    else
      "" # Default background color if status doesn't match
    end
  end

  def priority_string(priority)
    case priority
    when 1
      "Low"
    when 2
      "Medium"
    when 3
      "High"
    else
      "Unknown"
    end
  end

  def status_string(status)
    case status
    when 1
      "Pending"
    when 2
      "In Progress"
    when 3
      "Completed"
    else
      "Unknown"
    end
  end
  
end

app/views/tasks/_tasks_container.html.erb
<div class="container">
  <div class="text-center">
    <h2>My Tasks</h2>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="sortDropdown" data-bs-toggle="dropdown" aria-expanded="false">
        Sort By
      </button>
      <ul class="dropdown-menu" aria-labelledby="sortDropdown">
        <li><a class="dropdown-item" href="?sort=priority">Priority</a></li>
        <li><a class="dropdown-item" href="?sort=due_date">Due Date</a></li>
        <li><a class="dropdown-item" href="?sort=status">Status</a></li>        
      </ul>
    </div>
  </div>

  <div class="row mt-3">
    <% if @tasks.empty? %>
      <div class="col text-center">
        <h4 class="text-muted">You have not created any tasks yet.</h4>
        <%= link_to "Create Task", new_task_path, class: "btn btn-primary" %>
      </div>
    <% else %>
      <% @tasks.each_with_index do |task, index| %>
        <div class="col-md-4">
          <div class="card mb-3" onclick="window.location='<%= task_path(task) %>'" style="cursor: pointer">
            <div class="card-header" style="<%= task_status_background(task.status) %>"> <!-- Apply background color based on status -->
              <h5 class="card-title"><%= task.id.to_s + " - " + task.title %></h5>
            </div>
            <div class="card-body">
              <p class="card-text"><%= truncate(task.description, length: 100) %></p>
              <ul class="list-unstyled">
                <li><strong>Status:</strong> <%= status_string(task.status) %></li>
                <li><strong>Priority:</strong> <%= priority_string(task.priority) %></li>
                <li><strong>Due Date:</strong> <%= task.due_date %></li>
                <li><strong>Created at:</strong> <%= task.created_at.strftime("%d-%m-%Y %H:%M") %></li>
                <li><strong>Updated at:</strong> <%= task.updated_at.strftime("%d-%m-%Y %H:%M") %></li>
              </ul>
            </div>
          </div>
        </div>
        <% if ((index + 1) % 3 == 0) %>
          </div><div class="row mt-3">
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tasks/assigned_tasks.html.erb
<div class="container">
  <div class="text-center">
    <h2>Assigned Tasks</h2>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="sortDropdown" data-bs-toggle="dropdown" aria-expanded="false">
        Sort By
      </button>
      <ul class="dropdown-menu" aria-labelledby="sortDropdown">
        <li><a class="dropdown-item" href="?sort=priority">Priority</a></li>
        <li><a class="dropdown-item" href="?sort=due_date">Due Date</a></li>
        <li><a class="dropdown-item" href="?sort=status">Status</a></li>
      </ul>
    </div>
  </div>

  <div class="row mt-3">
    <% if @assigned_tasks.empty? %>
      <div class="col text-center">
        <h4 class="text-muted">There are no tasks assigned to you.</h4>
      </div>
    <% else %>
      <% @assigned_tasks.each_with_index do |task, index| %>
        <div class="col-md-4">
          <div class="card mb-3" onclick="window.location='<%= show_assigned_task_path(task) %>'" style="cursor: pointer">
            <div class="card-header" style="<%= task_status_background(task.status) %>"> <!-- Apply background color based on status -->
              <h5 class="card-title"><%= task.id.to_s + " - " + task.title %></h5>
            </div>
            <div class="card-body">
              <p class="card-text"><%= truncate(task.description, length: 100) %></p>
              <ul class="list-unstyled">
                <li><strong>Status:</strong> <%= status_string(task.status) %></li>
                <li><strong>Priority:</strong> <%= priority_string(task.priority) %></li>
                <li><strong>Due Date:</strong> <%= task.due_date %></li>
                <li><strong>Created at:</strong> <%= task.created_at.strftime("%d-%m-%Y %H:%M") %></li>
                <li><strong>Updated at:</strong> <%= task.updated_at.strftime("%d-%m-%Y %H:%M") %></li>
              </ul>
            </div>
          </div>
        </div>
        <% if ((index + 1) % 3 == 0) %>
          </div><div class="row mt-3">
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<% content_for(:title, "Edit task | " + @task.title ) %>
<h1 class="mb-4">Edit Task</h1>

<div class="container">
  <%= form_with(model: @task, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control", disabled: true %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control", rows: 5 %>
    </div>

    <div class="mb-3">
      <%= form.label :status, class: "form-label" %>
      <%= form.select :status, [["Pending", 1]], {}, class: "form-select" %>
    </div>

    <div class="mb-3">
      <%= form.label :priority, class: "form-label" %>
      <%= form.select :priority, [["Low", 1], ["Medium", 2], ["High", 3]], {}, class: "form-select" %>
    </div>

    <div class="mb-3">
      <%= form.label :due_date, class: "form-label" %>
      <%= form.date_field :due_date, class: "form-control" %>
    </div>

    <div class="mb-3 text-center">
      <%= form.submit 'Update Task', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/tasks/index.html.erb
<% content_for(:title, "My Tasks | " + Current.user.first_name + " " + Current.user.last_name) %>
<%= render partial: 'tasks_container', locals: { tasks: @tasks } %>

app/views/tasks/new.html.erb
<% content_for(:title, "Create Task | #{Current.user.first_name} #{Current.user.last_name}") %>

<div class="container">
  <h1 class="mb-4">Create Task</h1>

  <%= form_with model: @task, url: tasks_path do |form| %>
    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control", placeholder: "Enter task title" %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, rows: 5, class: "form-control", placeholder: "Enter task description" %>
    </div>  

    <div class="row mb-3">
      <div class="col-md-6">
        <%= form.label :department, class: "form-label" %>
        <%= form.select :department_id, options_for_select(@departments), {}, class: "form-select", id: "department-select" %>
      </div>

      <div class="col-md-6">
        <%= form.label :assign_to, class: "form-label" %>
        <%= form.select :assignee_id, options_for_select([], @task.assignee), {}, class: "form-select", id: "assign-to-user-select" %>
      </div>

    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= form.label :status, class: "form-label" %>
        <%= form.select :status, [["Pending", 1]], {}, class: "form-select"%>
      </div>

      <div class="col-md-6">
        <%= form.label :priority, class: "form-label" %>
        <%= form.select :priority, [["Low", 1], ["Medium", 2], ["High", 3]], {}, class: "form-select" %>
      </div>
    </div>

    <div class="mb-3">
      <%= form.label :due_date, class: "form-label" %>
      <%= form.date_field :due_date, class: "form-control", placeholder: "Select due date" %>
    </div>

    <div class="mb-3">
      <%= form.submit "Create Task", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function() {                      // run script after DOM fully loaded
    $('#department-select').change(function() {       // event handler
      var departmentId = $(this).val();
      $.ajax({
        url: '/users_by_department',
        method: 'GET',
        data: { department_id: departmentId },
        success: function(data) {
          var options = '';
          data.forEach(function(user) {
            options += '<option value="' + user.id + '">' + user.full_name + ' (' + user.email + ')</option>';
          });
          $('#assign-to-user-select').html(options);
        },
        error: function(xhr, status, error) {
          console.error(error);
        }
      });
    });
  });
</script>

app/views/tasks/non_verified_tasks.html.erb
<% content_for(:title, "Non-Verified Tasks | #{Current.user.email}") %>

<div class="container">
  <h1 class="mb-4">Non-Verified Tasks</h1>

  <div class="row">
    <% @non_verified_tasks.each do |task| %>
      <div class="col-md-4">
        <div class="card mb-3">
          <div class="card-header" style="<%= task_status_background(task.status) %>">
            <h5 class="card-title"><%= task.title %></h5>
          </div>
          <div class="card-body">
            <p class="card-text"><strong>Description:</strong> <%= task.description %></p>
            <ul class="list-unstyled">
              <li><strong>Task ID:</strong> <%= task.id %></li>
              <li><strong>Status:</strong> <%= status_string(task.status) %></li>
              <li><strong>Priority:</strong> <%= priority_string(task.priority) %></li>
              <li><strong>Assigned to:</strong> <%= task.assignee.full_name %></li>
              <li><strong>Due Date:</strong> <%= task.due_date %></li>
              <li><strong>Created at:</strong> <%= task.created_at.strftime("%d-%m-%Y %H:%M") %></li>
              <li><strong>Updated at:</strong> <%= task.updated_at.strftime("%d-%m-%Y %H:%M") %></li>
            </ul>
            <% if task.verifier_id.nil? && task.user_id != Current.user.id %>
              <%= link_to "Approve", approve_task_path(task), data: { turbo_method: :put }, class: "btn btn-success mr-2" %>
            <% end %>
            <%= link_to "View Details", show_for_approval_path(task), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<% content_for(:title, @task.id.to_s + " - " + @task.title + " | " + Current.user.first_name + " " + Current.user.last_name ) %>

<div class="container">
  <div class="card mt-4">
    <div class="card-header" style="<%= task_status_background(@task.status) %>">
      <h5 class="card-title"><%= @task.title %></h5>
    </div>
    <div class="card-body">
      <p class="card-text"><strong>Description:</strong></p>
      <p><%= @task.description %></p>
      <ul class="list-unstyled">
        <li><strong>Task ID:</strong> <%= @task.id %></li>
        <li><strong>Status:</strong> <%= status_string(@task.status) %></li>
        <li><strong>Priority:</strong> <%= priority_string(@task.priority) %></li>
        <li><strong>Department:</strong> <%= @task.department.name %></li>
        <li><strong>Due Date:</strong> <%= @task.due_date %></li>
        <li><strong>Assigned to:</strong> <%= @task.assignee.first_name + " " + @task.assignee.last_name + " (" + @task.assignee.email + ")" %></li>        
        <% if @task.verifier_id.present? %>
          <li><strong>Verified by:</strong> <%= @task.verifier.first_name + " " + @task.verifier.last_name %> (<%= @task.verifier.email %>)</li>
        <% end %>
        <li><strong>Created at:</strong> <%= @task.created_at.strftime("%d-%m-%Y %H:%M") %></li>
        <li><strong>Updated at:</strong> <%= @task.updated_at.strftime("%d-%m-%Y %H:%M") %></li>
      </ul>
      <div class="btn-group" role="group">
        <%= link_to "Edit Task", edit_task_path(@task), class: "btn btn-primary mr-2" %>
        <%= link_to "Delete", task_path(@task), data: { confirm: "Are you sure you want to delete this task?", turbo_method: :delete }, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show_assigned_task.html.erb
<% content_for(:title, @task.title + " | " + Current.user.email ) %>

<div class="container">
  <div class="card mt-4">
    <div class="card-header" style="<%= task_status_background(@task.status) %>">
      <h5 class="card-title"><%= @task.title %></h5>
    </div>
    <div class="card-body">
      <p class="card-text"><strong>Description:</strong></p>
      <p><%= @task.description %></p>
      <ul class="list-unstyled">
        <li><strong>Task ID:</strong> <%= @task.id %></li>
        <li><strong>Status:</strong> <%= status_string(@task.status) %></li>
        <li><strong>Priority:</strong> <%= priority_string(@task.priority) %></li>
        <li><strong>Department:</strong> <%= @task.department.name %></li>
        <li><strong>Due Date:</strong> <%= @task.due_date %></li>
        <li><strong>Assigned to:</strong> <%= @task.assignee.first_name + " " + @task.assignee.last_name + " (" + @task.assignee.email + ")" %></li>
        <% if @task.verifier_id.present? %>
          <li><strong>Verified by:</strong> <%= @task.verifier.first_name + " " + @task.verifier.first_name %> (<%= @task.verifier.email %>)</li>
        <% end %>
        <li><strong>Created at:</strong> <%= @task.created_at.strftime("%d-%m-%Y %H:%M") %></li>
        <li><strong>Updated at:</strong> <%= @task.updated_at.strftime("%d-%m-%Y %H:%M") %></li>
      </ul>
      <% if @task.verifier_id.present? && @task.status == 3%>
        <div class="btn-group" role="group">
          <%= link_to "This task is completed.", show_assigned_task_path(@task), class: "btn btn-info" %>
        </div>
      <% elsif @task.verifier_id.present? && @task.status == 2%>
        <div class="btn-group" role="group">
          <%= link_to "Mark task as completed", mark_complete_path(@task), data: { turbo_method: :put }, class: "btn btn-success" %>
        </div>
      <% elsif @task.verifier_id.present? %>
        <div class="btn-group" role="group">
          <%= link_to "Acknowledge task", acknowledge_task_path(@task), data: { turbo_method: :put }, class: "btn btn-primary" %>
        </div>
      <% else %>
        <div class="btn-group" role="group">
          <%= link_to "Waiting for verification", show_assigned_task_path(@task), class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show_for_approval.html.erb
<% content_for(:title, @task.title + " | " + Current.user.email ) %>

<div class="container">
  <div class="card mt-4">
    <div class="card-header" style="<%= task_status_background(@task.status) %>">
      <h5 class="card-title"><%= @task.title %></h5>
    </div>
    <div class="card-body">
      <p class="card-text"><strong>Description:</strong></p>
      <p><%= @task.description %></p>
      <ul class="list-unstyled">
        <li><strong>Task ID:</strong> <%= @task.id %></li>
        <li><strong>Status:</strong> <%= status_string(@task.status) %></li>
        <li><strong>Priority:</strong> <%= priority_string(@task.priority) %></li>
        <li><strong>Department:</strong> <%= @task.department.name %></li>
        <li><strong>Due Date:</strong> <%= @task.due_date %></li>
        <li><strong>Assigned to:</strong> <%= @task.assignee.first_name + " " + @task.assignee.last_name + " (" + @task.assignee.email + ")" %></li>        
        <% if @task.verifier_id.present? %>
          <li><strong>Verified by:</strong> <%= @task.verifier.first_name + " " + @task.verifier.first_name %> (<%= @task.verifier.email %>)</li>
        <% end %>
        <li><strong>Created at:</strong> <%= @task.created_at.strftime("%d-%m-%Y %H:%M") %></li>
        <li><strong>Updated at:</strong> <%= @task.updated_at.strftime("%d-%m-%Y %H:%M") %></li>
      </ul>
      <% if @task.verifier_id.nil? && @task.user_id != Current.user.id %>
        <%= form_with(model: @task, url: approve_task_path(@task), method: :put) do |form| %>
          <%= form.submit "Approve", class: "btn btn-success" %>
        <% end %>

      <% end %>
    </div>
  </div>
</div>