config/routes.rb
Rails.application.routes.draw do
  get "about", to:"about#index"
  # get "", to: "main#index"
  root to: "main#index"

  get "dashboard", to: "dashboard#index"

  get "profile", to: "profile#index"

  get "users_by_department", to: "users#users_by_department"
  
  get "login", to: "session#new"
  post "login", to: "session#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"
  
  get "signup", to: "registrations#new"
  post "signup", to: "registrations#create"
  
  delete "logout", to: "session#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "/non_verified_tasks", to: "tasks#non_verified_tasks"
  get "/non_verified_tasks/:id", to: "tasks#show_for_approval", as: "show_for_approval"
  put "/non_verified_tasks/:id/approve", to: "tasks#approve", as: "approve_task"

  get "/assigned_tasks", to: "tasks#assigned_tasks"
  get "/assigned_tasks/:id", to: "tasks#show_assigned_task", as: "show_assigned_task"
  put "/assigned_tasks/:id/mark_done", to: "tasks#mark_complete", as: "mark_complete"
  put "/assigned_tasks/:id/acknowledge_task", to: "tasks#acknowledge_task", as: "acknowledge_task"
  resources :tasks
  
  resources :users
  # Error routes
  # match '/404', to: 'errors#not_found', via: :all
  # match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def index
    @user = User.new
  end
  
  def new
  end

  def create
    user = User.find_by(email: params[:email]) 
    if user.present? && user.authenticate(params[:password]) # Todo
      session[:user_id] = user.id
      redirect_to tasks_path, notice: "Logged in successfully."
    else
      flash.now[:alert] = "Invalid email or password. Please try again."
      render :new, alert: "Invalid email or password."  
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out successfully!"
  end

end

app/views/session/new.html.erb
<% content_for(:title, "Sign In | Task Manager") %>

<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title text-center mb-4">Sign In</h1>

          <!-- Image -->
          <div class="text-center mb-4">
            <img src="https://abhishekkamble.s3.ap-south-1.amazonaws.com/portfolio-images/Sample_User_Icon.png" alt="Logo" class="rounded-circle" style="width: 100px; height: 100px;">
          </div>

          <%= form_with model: @user, url: login_path do |form| %>
            <div class="mb-3">
              <%= form.label :email, class: "form-label" %>
              <%= form.text_field :email, class: "form-control", placeholder: "Enter your email" %>
            </div>
            <div class="mb-3">
              <%= form.label :password, class: "form-label" %>
              <%= form.password_field :password, class: "form-control", placeholder: "Enter your password" %>
              <%= link_to "Forgot your password?", password_reset_path, class: "d-block mt-2" %>
            </div>
            <div class="mb-3 text-center">
              <%= form.submit "Login", class: "btn btn-primary" %>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>