config/routes.rb
Rails.application.routes.draw do
  get "about", to:"about#index"
  # get "", to: "main#index"
  root to: "main#index"

  get "dashboard", to: "dashboard#index"

  get "profile", to: "profile#index"

  get "users_by_department", to: "users#users_by_department"
  
  get "login", to: "session#new"
  post "login", to: "session#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"
  
  get "signup", to: "registrations#new"
  post "signup", to: "registrations#create"
  
  delete "logout", to: "session#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "/non_verified_tasks", to: "tasks#non_verified_tasks"
  get "/non_verified_tasks/:id", to: "tasks#show_for_approval", as: "show_for_approval"
  put "/non_verified_tasks/:id/approve", to: "tasks#approve", as: "approve_task"

  get "/assigned_tasks", to: "tasks#assigned_tasks"
  get "/assigned_tasks/:id", to: "tasks#show_assigned_task", as: "show_assigned_task"
  put "/assigned_tasks/:id/mark_done", to: "tasks#mark_complete", as: "mark_complete"
  put "/assigned_tasks/:id/acknowledge_task", to: "tasks#acknowledge_task", as: "acknowledge_task"
  resources :tasks
  
  resources :users
  # Error routes
  # match '/404', to: 'errors#not_found', via: :all
  # match '/500', to: 'errors#internal_server_error', via: :all
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <% if type == "notice" %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% elsif type == "alert" %>  
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <% if Current.user == nil %>
      <a class="navbar-brand" href="/">Home</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
     <% end %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Created Tasks", tasks_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Assigned Tasks", assigned_tasks_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pending approvals", non_verified_tasks_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Task", new_task_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", profile_path, class: "nav-link" %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "About Us", about_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-item navbar-text mx-2">
          Logged in as: <strong> <%= link_to Current.user.email, edit_password_path %> </strong>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class: "btn
          btn-danger" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", signup_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>